/* tslint:disable */
/* eslint-disable */
/**
 * Test
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Cat
 */
export interface Cat {
    /**
     * 
     * @type {boolean}
     * @memberof Cat
     */
    huntsDo?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Cat
     */
    ageThis?: number;
    /**
     * 
     * @type {string}
     * @memberof Cat
     */
    petType: string;
}

export function CatFromJSON(json: any): Cat {
    return CatFromJSONTyped(json, false);
}

export function CatFromJSONTyped(json: any, ignoreDiscriminator: boolean): Cat {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'huntsDo': !exists(json, 'hunts_do') ? undefined : json['hunts_do'],
        'ageThis': !exists(json, 'age_this') ? undefined : json['age_this'],
        'petType': json['pet_type'],
    };
}

export function CatToJSON(value?: Cat | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hunts_do': value.huntsDo,
        'age_this': value.ageThis,
        'pet_type': value.petType,
    };
}


