/* tslint:disable */
/* eslint-disable */
/**
 * Test
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Cat,
    Dog,
    CatFromJSONTyped,
    CatToJSON,
    DogFromJSONTyped,
    DogToJSON,
} from './';

/**
 * @type MyPet
 * 
 * @export
 */
export type MyPet = { petType: 'Cat' } & Cat | { petType: 'Dog' } & Dog;

export function MyPetFromJSON(json: any): MyPet {
    return MyPetFromJSONTyped(json, false);
}

export function MyPetFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyPet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['petType']) {
        case 'Cat':
            return {...CatFromJSONTyped(json, true), petType: 'Cat'};
        case 'Dog':
            return {...DogFromJSONTyped(json, true), petType: 'Dog'};
        default:
            throw new Error(`No variant of MyPet exists with 'petType=${json['petType']}'`);
    }
}

export function MyPetToJSON(value?: MyPet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['petType']) {
        case 'Cat':
            return CatToJSON(value);
        case 'Dog':
            return DogToJSON(value);
        default:
            throw new Error(`No variant of MyPet exists with 'petType=${value['petType']}'`);
    }
}

